### ISSUE TITLE
Fix inputMismatches on the files

### ISSUE THREAD

**Issue by matuella** [matuella/vendaDeProdutos#2]
Fix the inputMismatches in the each respective switch (change int into String):
*depositoNaConta
*alterar e ver Produto
*alterar e pesquisar Cliente

**Comment by RafaGH** [comment]
Fazendo =D

**Comment by RafaGH** [comment]
RepositorioCliente/ClienteView feito!

**Comment by RafaGH** [comment]
Feito, todos os "op"s dos Switchs trocados pra String!

**Comment by matuella** [comment]
BOA RAPAIZ!
